// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID    `json:"id"`
	Password  string       `json:"password"`
	Cpf       string       `json:"cpf"`
	Email     string       `json:"email"`
	Phone     string       `json:"phone"`
	Name      string       `json:"name"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	NickName  string       `json:"nick_name"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
